#!/bin/bash

declare -a regionList=("us-east-1" "us-west-1" "us-west-2" "ap-northeast-1" "ap-northeast-2" "ap-northeast-3" "ap-south-1" "ap-southeast-1" "ap-southeast-2" "ca-central-1" "cn-north-1" "cn-northwest-1" "eu-central-1" "eu-west-1" "eu-west-2" "eu-west-3" "sa-east-1")
read -p "Enter the instance Hostname: " hostname
shortcode=${hostname:0:4}
region="eu-west-1"
regionExists=false
shortcode=$(echo $shortcode | awk '{print toupper($0)}')

read -p "Enter the region. Default is $region : Leave blank to set default: " regionResponse
while [[ $regionExists = false ]]; do
	
	if [[ -n "$regionResponse" ]]; then
		for i in "${regionList[@]}"; do	
						
			if [[ "$i" == "$region" ]]; then
				regionExists=true
				region=$regionResponse
				break
			fi
		
		done
	else
		regionExists=true
		echo "test2"
	fi
done

if [[ "$regionExists" = false ]]; then
	read -p "Region does not exist. Make sure it is in lower case. e.g. eu-west-1: " regionResponse
fi

shortcodeConfigCheck=$(grep -rnw "$HOME/.aws/config" -e "$shortcode")
if [[ -z $shortcodeConfigCheck ]]; then
	echo "$shortcode does not exist in $HOME/.aws/config . You will need to add it."
	read -p "Would you like to do that now? (y/n): " addConfigResponse
	while [[ "$addConfigResponse" != [YyNn] ]]; do
		read -p "Answer with y or n! Please!! " addConfigResponse
	done
fi

if [[ "$addConfigResponse" == [Yy] ]]; then
	echo "I am adding your profile. just a moment."
	read -p "What is your cr-prod user name? eg. first.last@cloudreach.com " awsUserName
	read -p "What is the account number associated with the shortcode? " accNumber
	re='^[0-9]+$'
	while ! [[ $accNumber =~ $re ]]; do
		read -p "You must enter a number: " accNumber
	done
	#building profile
	echo "" >> $HOME/.aws/config
	echo "[profile $shortcode]" >> $HOME/.aws/config
	echo "role_arn = arn:aws:iam::$accNumber:role/CloudreachAdminRole" >> $HOME/.aws/config
	echo "source_profile = default" >> $HOME/.aws/config
	echo "mfa_serial = arn:aws:iam::540625458825:mfa/$awsUserName" >> $HOME/.aws/config
	echo "output = json" >> $HOME/.aws/config
	echo "region = $region" >> $HOME/.aws/config
	echo "Profile has been created"
fi

export AWS_PROFILE=$shortcode
export AWS_REGION=$region
echo "Your AWS_PROFILE is set to $AWS_PROFILE"
echo "Your AWS_REGION is set to $AWS_REGION"

read -p "Try running a command: " awsCommand

eval $awsCommand

read -p "Did the command succeed? (y/n): " awsCommandSuccess
if [[ "$addConfigResponse" == [Nn] ]]; then
	linesTotal=$(wc -l $HOME/.aws/config | awk '{print $1}')
	linesFinal="$(($linesTotal-7))"
	head -n $linesFinal $HOME/.aws/config > $HOME/.aws/config
	unset -u
fi

echo "It is time for me to end myself"


